<?php
$name = $_POST["name"];
$phone = $_POST["phone"];
$subject = $_POST["subject"];
$message = $_POST["message"];

$phone = urlencode("$phone");

try {
    $textMessage = "<b>Ім'я:</b> <u>$name</u> \n<b>Телефон:</b> $phone\n<b>Тема:</b> <u>$subject</u> \n<b>Повідомлення:</b> <u>$message</u> \n";
} catch (\Throwable$th){
    $textMessage = "ERROR IN MESSAGE";
}

    $token = "8310805356:AAFkb3tTMNlU3ahGvU68IzdLhRHOgPa80QY"; // Token generated by bor father
    $chat_id = -1003362828805; //Number of active chat from https:api.telegram.org/botToken<>/getUpdates


    $textMessage = urlencode("$textMessage");
   // echo($textMessage);

    $urlQuery = "https://api.telegram.org/bot". $token ."/sendMessage?chat_id=". $chat_id ."&text=" . $textMessage . "&parse_mode=HTML";
    $result = file_get_contents($urlQuery);
?>
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="style/style.css">
    <title>Дякуємо! Заявка отримана</title>

    <style>
        body {
            font-family: "Roboto", sans-serif;
            background: #f5f7fa;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

    </style>
</head>
<body>

<div class="card">
    <h1 class ="thanks">Дякуємо за звернення!</h1>

 <div class="item"><span>Ім'я:</span> <?php echo $name; ?></div>
    <div class="item"><span>Телефон:</span> <?php echo $phone; ?></div>
    <div class="item"><span>Тема:</span> <?php echo $subject; ?></div>
    <div class="item"><span>Повідомлення:</span> <?php echo $message; ?></div>

    <a class="btn" href="/">Повернутися на головну</a>
</div>

</body>
</html>

